### ISSUE TITLE
Dataset dyml

### ISSUE THREAD

**Issue by stqwzr** [elias-ramzi/HAPPIER#3]
Hi, thank you for sharing dataset. But, link doesn't work? How can i reach to dataset?

**Comment by elias-ramzi** [comment]
Hi, I found the dataset on this github repository : https://github.com/SupetZYK/DynamicMetricLearning.
It is the repository from this paper: Dynamic Metric Learning: Towards a Scalable Metric Space
to Accommodate Multiple Semantic Scales (https://openaccess.thecvf.com/content/CVPR2021/papers/Sun_Dynamic_Metric_Learning_Towards_a_Scalable_Metric_Space_To_Accommodate_CVPR_2021_paper.pdf).

I found that the onedrive link does not work anymore. Maybe you can try the Baidu link.

Let me know if this works for you.

**Comment by stqwzr** [comment]
Hi, thank you!
Figured out with baidu link.

**Comment by kennyvoo** [comment]
Do you guys have the label id to class mapping of the car dataset?
