### ISSUE TITLE
About the proxy settings of the CSL loss

### ISSUE THREAD

**Issue by DavidLeexxxx** [elias-ramzi/HAPPIER#6]
Thanks for your work and answer before. Currently I'm focusing on the prior work: Dynamic Metric Learning: Towards a Scalable Metric Space to Accommodate Multiple Semantic Scales. Noticing that you have impelemented the CSL loss paradim in this work which the origin author didn't provide it, I briefly read part of the impelementation. In the original paper, the author mentioned they use a hard mining strategy, which indicates that the proxy embeddings number equals to the fine-grained level class numbers and the coaser level classes' embedding refer to their subsets. But the impelementation in this code seems that the proxy embedding number equals to the total class number(like flatten the classes at each level). I am a little confused about this part.

**Comment by elias-ramzi** [comment]
Hi,

In the implementation the number of proxies is equal to the number of unique fine-grained classes.

This is tested here: https://github.com/elias-ramzi/HAPPIER/blob/5af91b3ac6c216a936232da33b42af7efaba5c6b/happier/losses/csl_loss.py#LL77C9-L77C62

**Comment by DavidLeexxxx** [comment]
Got it, sorry i didn't read the code carefully before, here you use the logsumexp to simulate the max operation amang the negative catogories i guess which is corresponded to the hard mining strategy in CSL.
